"""
Continuum Lab — Mathematical Physics & Fourier Geometry
Complex Fourier Series Analysis for Canonical Geometric Shapes:
  1. Circle (Pure fundamental harmonic N = 1, SO(2) continuous symmetry)
  2. 5-Pointed Star (Dihedral symmetry D_5, harmonics n = 1, -4, 6, -9, 11...)
  3. Regular Octagon (Dihedral symmetry D_8, harmonics n = 1, -7, 9, -15, 17...)

Provides analytical & numerical Fourier coefficient extraction, epicycle chain kinematics,
and exact closed-form parametric trajectory evaluations.
"""

import numpy as np
from typing import List, Tuple, Dict


class ShapeFourierSeries:
    """
    Computes and evaluates truncated Complex Fourier series:
    z_N(t) = sum_{k=1}^N c_{n_k} * exp(i * n_k * t)
    """

    def __init__(self, shape_name: str, radius: float = 1.0):
        self.shape_name = shape_name.lower()
        self.radius = radius
        self.harmonics = self._get_harmonic_coefficients()

    def _get_harmonic_coefficients(self) -> List[Tuple[int, float, float]]:
        """
        Returns list of (frequency_n, amplitude, phase_rad) sorted by amplitude.
        """
        if self.shape_name in ["circle", "circulo"]:
            # Pure fundamental harmonic (Single epicycle)
            return [
                (1, self.radius, 0.0)
            ]

        elif self.shape_name in ["star", "estrella"]:
            # 5-pointed star with D_5 dihedral symmetry
            # Alternating cusps generated by n = 1, -4, 6, -9, 11, -14, 16...
            r0 = self.radius * 0.687
            return [
                (1, r0, 0.0),
                (-4, r0 * 0.242, 0.0),
                (6, r0 * 0.107, 0.0),
                (-14, r0 * 0.020, 0.0),
                (16, r0 * 0.015, 0.0),
                (-9, r0 * 0.012, 0.0),
                (11, r0 * 0.008, 0.0),
            ]

        elif self.shape_name in ["octagon", "octogono", "octágono"]:
            # Regular 8-sided polygon with D_8 dihedral symmetry
            # Harmonics n = 1, -7, 9, -15, 17... decaying as 1/n^2
            r0 = self.radius * 0.950
            return [
                (1, r0, 0.0),
                (-7, r0 / 49.0, 0.0),
                (9, r0 / 81.0, 0.0),
                (-15, r0 / 225.0, 0.0),
                (17, r0 / 289.0, 0.0),
                (-23, r0 / 529.0, 0.0),
                (25, r0 / 625.0, 0.0),
            ]
        else:
            raise ValueError(f"Unknown shape name: {self.shape_name}")

    def evaluate_point(self, t: float, num_terms: int = None) -> complex:
        """Evaluates complex position z(t) for a given truncation order."""
        terms = self.harmonics[:num_terms] if num_terms else self.harmonics
        z = 0.0 + 0.0j
        for freq, amp, phase in terms:
            z += amp * np.exp(1j * (freq * t + phase))
        return z

    def get_curve_points(self, num_points: int = 400, num_terms: int = None) -> np.ndarray:
        """Returns array of (x, y) coordinates for t in [0, 2*pi]."""
        t_vals = np.linspace(0, 2 * np.pi, num_points)
        coords = np.zeros((num_points, 2))
        for i, t in enumerate(t_vals):
            z = self.evaluate_point(t, num_terms)
            coords[i, 0] = z.real
            coords[i, 1] = z.imag
        return coords

    def get_epicycles_kinematics(self, t: float, num_terms: int = None) -> List[Dict]:
        """
        Returns kinematics for drawing rotating epicycle phasors:
        List of dicts with 'center', 'radius', 'tip', 'frequency'.
        """
        terms = self.harmonics[:num_terms] if num_terms else self.harmonics
        epicycles = []
        current_center = np.array([0.0, 0.0, 0.0])

        for freq, amp, phase in terms:
            vector = np.array([
                amp * np.cos(freq * t + phase),
                amp * np.sin(freq * t + phase),
                0.0
            ])
            tip = current_center + vector
            epicycles.append({
                "center": current_center.copy(),
                "radius": amp,
                "tip": tip.copy(),
                "freq": freq
            })
            current_center = tip

        return epicycles

    def get_latex_formula(self, lang: str = "ES") -> str:
        """Returns LaTeX mathematical formulation of the Fourier series."""
        if self.shape_name in ["circle", "circulo"]:
            return r"z(t) = R \, e^{i t} \quad (N = 1 \text{ Arm\'onico Puro})" if lang == "ES" else r"z(t) = R \, e^{i t} \quad (N = 1 \text{ Pure Harmonic})"

        elif self.shape_name in ["star", "estrella"]:
            if lang == "ES":
                return r"z_N(t) \approx r_0 \left[ e^{i t} + \frac{1}{4} e^{-i 4 t} + \frac{1}{9} e^{i 6 t} + \dots \right] \quad (D_5)"
            else:
                return r"z_N(t) \approx r_0 \left[ e^{i t} + \frac{1}{4} e^{-i 4 t} + \frac{1}{9} e^{i 6 t} + \dots \right] \quad (D_5)"

        elif self.shape_name in ["octagon", "octogono", "octágono"]:
            if lang == "ES":
                return r"z_N(t) = R_0 \sum_{k} \frac{(-1)^k}{(8k \pm 1)^2} \, e^{i (8k \pm 1) t} \quad (D_8)"
            else:
                return r"z_N(t) = R_0 \sum_{k} \frac{(-1)^k}{(8k \pm 1)^2} \, e^{i (8k \pm 1) t} \quad (D_8)"
        return ""
